function [condition_number, currents, d_vectors] = resistors(R, V1, V2, V3, V4)
% RESISTORS - Find mesh current values of a resistor network for different voltages
%
% Circuit diagram:
% https://drive.google.com/open?id=17zNiqFQ_bE2QyYtNTTr_uVcvRdw4f2lC
%
% Input
%   R: a vector of 8 elements corresponding to the 8 resistor values in ohms
%   V1: voltage of DC source 1 (scalar)
%   V2: voltage of DC source 2 (scalar or vector)
%   V3: voltage of DC source 3 (scalar)
%   V4: voltage of DC source 4 (scalar)
%
% Output
%   condition_number: the condition of the coefficient resistor matrix
%   currents: a matrix of mesh current values in amperes
%   d_vectors: a matrix of intermediate calculations
%
% Both result matrices are formed as concatenated row vectors, each column
% represents a solution of the mesh current (i1 - i4) and each row
% is the solution for a different given voltage for V2.

    % Check arguments
    narginchk(5, 5);

    if length(R) ~= 8
        error('The resistor vector must have 8 elements.');
    end

    % Coefficient matrix for a resistor network
    coeff_matrix = ...
        [(R(1)+R(2)+R(6)) -R(1)                  -R(2)            -R(6);
          R(1)            -(R(1)+R(3)+R(4)+R(8))  R(4)             R(8);
         -R(2)            -R(4)                  (R(2)+R(4)+R(5))  0;
         -R(6)            -R(8)                   0               (R(6)+R(7)+R(8))];

    % Calculate the condition of the matrix, which is used to check how
    % sensitive the solutions are to small changes in the resistor values.
    % If the condition number is large, the matrix is ill-conditioned.
    % If it is small, the matrix is well-conditioned.
    condition_number = cond(coeff_matrix);

    % Perform LU factorization of the coefficient matrix, so that the solutions
    % for many different right-hand side vectors of voltages can be calculated
    % efficiently.
    [lower_coeff, upper_coeff, perm_coeff] = lu(coeff_matrix);

    % Pre-allocate result matrices
    % d_vectors are intermediary results
    % currents are the final results for the mesh current values
    % Both result matrices are formed as concatenated row vectors, each column
    % represents a solution of the mesh current (i1 - i4) and each row
    % is the solution for a different given voltage for V2.
    d_vectors = zeros(length(V2), length(coeff_matrix));
    currents  = zeros(length(V2), length(coeff_matrix));

    % Find solutions to the matrix for each set of voltage values generated by
    % the values of V2 given.
    for it = 1:length(V2)
        voltages = [V1; V2(it); V3; (V2(it) - V4)];
        d_vectors(it, :) = lower_coeff \ (perm_coeff * voltages);
        currents(it, :) = upper_coeff \ d_vectors(it, :)';
    end
end
